services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    networks:
      - infra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.arquitetodebolso.com.br`)"
      - "traefik.http.routers.n8n.tls=true"
      - "traefik.http.routers.n8n.tls.certresolver=lets-encrypt"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.docker.network=infra"
    restart: always
    environment:
      - N8N_HOST=n8n.arquitetodebolso.com.br
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.arquitetodebolso.com.br/
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

networks:
  infra:
    external: true
  signoz-net:
    external: true
